### ISSUE TITLE
Should target_end_date values include reference_date + horizons?

### ISSUE THREAD

**Issue by annakrystalli** [hubverse-org/example-complex-forecast-hub#30]
It seems to me that the maximum `target_end_date` `"2023-05-27"` https://github.com/Infectious-Disease-Modeling-Hubs/example-complex-forecast-hub/blob/1c68ad69a3f8a58c89e64234b700b98633501554/hub-config/tasks.json#L105 is equal to to the maximum `reference_date` https://github.com/Infectious-Disease-Modeling-Hubs/example-complex-forecast-hub/blob/1c68ad69a3f8a58c89e64234b700b98633501554/hub-config/tasks.json#L23

Should it not be the maximum  `reference_date` + 1 week * each potential horizon?

**Comment by elray1** [comment]
yes, thanks!  I just filed a PR to fix this at #31
